/* soapH.h
   Generated by gSOAP 2.8.3 from et.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef soap_write_LONG64
#define soap_write_LONG64(soap, data) ( soap_begin_send(soap) || soap_put_LONG64(soap, data, "long", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);

#ifndef soap_read_LONG64
#define soap_read_LONG64(soap, data) ( soap_begin_recv(soap) || !soap_get_LONG64(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);

#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

#ifndef soap_write_double
#define soap_write_double(soap, data) ( soap_begin_send(soap) || soap_put_double(soap, data, "double", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, const double *, const char*, const char*);

#ifndef soap_read_double
#define soap_read_double(soap, data) ( soap_begin_recv(soap) || !soap_get_double(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);

#ifndef SOAP_TYPE__ns1__saveSolutionRequest
#define SOAP_TYPE__ns1__saveSolutionRequest (29)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__saveSolutionRequest(struct soap*, const char*, int, const _ns1__saveSolutionRequest *, const char*);
SOAP_FMAC3 _ns1__saveSolutionRequest * SOAP_FMAC4 soap_in__ns1__saveSolutionRequest(struct soap*, const char*, _ns1__saveSolutionRequest *, const char*);

#ifndef soap_write__ns1__saveSolutionRequest
#define soap_write__ns1__saveSolutionRequest(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:saveSolutionRequest", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__saveSolutionRequest
#define soap_read__ns1__saveSolutionRequest(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__saveSolutionRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__saveSolutionRequest * SOAP_FMAC4 soap_get__ns1__saveSolutionRequest(struct soap*, _ns1__saveSolutionRequest *, const char*, const char*);

#define soap_new__ns1__saveSolutionRequest(soap, n) soap_instantiate__ns1__saveSolutionRequest(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__saveSolutionRequest(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__saveSolutionRequest * SOAP_FMAC2 soap_instantiate__ns1__saveSolutionRequest(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__saveSolutionRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__msg
#define SOAP_TYPE__ns1__msg (28)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__msg(struct soap*, const char*, int, const _ns1__msg *, const char*);
SOAP_FMAC3 _ns1__msg * SOAP_FMAC4 soap_in__ns1__msg(struct soap*, const char*, _ns1__msg *, const char*);

#ifndef soap_write__ns1__msg
#define soap_write__ns1__msg(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:msg", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__msg
#define soap_read__ns1__msg(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__msg(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__msg * SOAP_FMAC4 soap_get__ns1__msg(struct soap*, _ns1__msg *, const char*, const char*);

#define soap_new__ns1__msg(soap, n) soap_instantiate__ns1__msg(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__msg(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__msg * SOAP_FMAC2 soap_instantiate__ns1__msg(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__msg(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__marketSolution
#define SOAP_TYPE__ns1__marketSolution (27)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__marketSolution(struct soap*, const char*, int, const _ns1__marketSolution *, const char*);
SOAP_FMAC3 _ns1__marketSolution * SOAP_FMAC4 soap_in__ns1__marketSolution(struct soap*, const char*, _ns1__marketSolution *, const char*);

#ifndef soap_write__ns1__marketSolution
#define soap_write__ns1__marketSolution(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:marketSolution", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__marketSolution
#define soap_read__ns1__marketSolution(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__marketSolution(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__marketSolution * SOAP_FMAC4 soap_get__ns1__marketSolution(struct soap*, _ns1__marketSolution *, const char*, const char*);

#define soap_new__ns1__marketSolution(soap, n) soap_instantiate__ns1__marketSolution(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__marketSolution(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__marketSolution * SOAP_FMAC2 soap_instantiate__ns1__marketSolution(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__marketSolution(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__partySolution
#define SOAP_TYPE__ns1__partySolution (26)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__partySolution(struct soap*, const char*, int, const _ns1__partySolution *, const char*);
SOAP_FMAC3 _ns1__partySolution * SOAP_FMAC4 soap_in__ns1__partySolution(struct soap*, const char*, _ns1__partySolution *, const char*);

#ifndef soap_write__ns1__partySolution
#define soap_write__ns1__partySolution(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:partySolution", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__partySolution
#define soap_read__ns1__partySolution(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__partySolution(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__partySolution * SOAP_FMAC4 soap_get__ns1__partySolution(struct soap*, _ns1__partySolution *, const char*, const char*);

#define soap_new__ns1__partySolution(soap, n) soap_instantiate__ns1__partySolution(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__partySolution(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__partySolution * SOAP_FMAC2 soap_instantiate__ns1__partySolution(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__partySolution(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__solution
#define SOAP_TYPE__ns1__solution (25)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__solution(struct soap*, const char*, int, const _ns1__solution *, const char*);
SOAP_FMAC3 _ns1__solution * SOAP_FMAC4 soap_in__ns1__solution(struct soap*, const char*, _ns1__solution *, const char*);

#ifndef soap_write__ns1__solution
#define soap_write__ns1__solution(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:solution", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__solution
#define soap_read__ns1__solution(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__solution(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__solution * SOAP_FMAC4 soap_get__ns1__solution(struct soap*, _ns1__solution *, const char*, const char*);

#define soap_new__ns1__solution(soap, n) soap_instantiate__ns1__solution(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__solution(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__solution * SOAP_FMAC2 soap_instantiate__ns1__solution(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__solution(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__bid
#define SOAP_TYPE__ns1__bid (24)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__bid(struct soap*, const char*, int, const _ns1__bid *, const char*);
SOAP_FMAC3 _ns1__bid * SOAP_FMAC4 soap_in__ns1__bid(struct soap*, const char*, _ns1__bid *, const char*);

#ifndef soap_write__ns1__bid
#define soap_write__ns1__bid(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:bid", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__bid
#define soap_read__ns1__bid(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__bid(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__bid * SOAP_FMAC4 soap_get__ns1__bid(struct soap*, _ns1__bid *, const char*, const char*);

#define soap_new__ns1__bid(soap, n) soap_instantiate__ns1__bid(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__bid(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__bid * SOAP_FMAC2 soap_instantiate__ns1__bid(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__bid(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__saveBidResponse
#define SOAP_TYPE__ns1__saveBidResponse (23)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__saveBidResponse(struct soap*, const char*, int, const _ns1__saveBidResponse *, const char*);
SOAP_FMAC3 _ns1__saveBidResponse * SOAP_FMAC4 soap_in__ns1__saveBidResponse(struct soap*, const char*, _ns1__saveBidResponse *, const char*);

#ifndef soap_write__ns1__saveBidResponse
#define soap_write__ns1__saveBidResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:saveBidResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__saveBidResponse
#define soap_read__ns1__saveBidResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__saveBidResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__saveBidResponse * SOAP_FMAC4 soap_get__ns1__saveBidResponse(struct soap*, _ns1__saveBidResponse *, const char*, const char*);

#define soap_new__ns1__saveBidResponse(soap, n) soap_instantiate__ns1__saveBidResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__saveBidResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__saveBidResponse * SOAP_FMAC2 soap_instantiate__ns1__saveBidResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__saveBidResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__saveBidRequest
#define SOAP_TYPE__ns1__saveBidRequest (22)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__saveBidRequest(struct soap*, const char*, int, const _ns1__saveBidRequest *, const char*);
SOAP_FMAC3 _ns1__saveBidRequest * SOAP_FMAC4 soap_in__ns1__saveBidRequest(struct soap*, const char*, _ns1__saveBidRequest *, const char*);

#ifndef soap_write__ns1__saveBidRequest
#define soap_write__ns1__saveBidRequest(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:saveBidRequest", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__saveBidRequest
#define soap_read__ns1__saveBidRequest(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__saveBidRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__saveBidRequest * SOAP_FMAC4 soap_get__ns1__saveBidRequest(struct soap*, _ns1__saveBidRequest *, const char*, const char*);

#define soap_new__ns1__saveBidRequest(soap, n) soap_instantiate__ns1__saveBidRequest(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__saveBidRequest(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__saveBidRequest * SOAP_FMAC2 soap_instantiate__ns1__saveBidRequest(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__saveBidRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__auction
#define SOAP_TYPE__ns1__auction (21)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__auction(struct soap*, const char*, int, const _ns1__auction *, const char*);
SOAP_FMAC3 _ns1__auction * SOAP_FMAC4 soap_in__ns1__auction(struct soap*, const char*, _ns1__auction *, const char*);

#ifndef soap_write__ns1__auction
#define soap_write__ns1__auction(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:auction", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__auction
#define soap_read__ns1__auction(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__auction(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__auction * SOAP_FMAC4 soap_get__ns1__auction(struct soap*, _ns1__auction *, const char*, const char*);

#define soap_new__ns1__auction(soap, n) soap_instantiate__ns1__auction(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__auction(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__auction * SOAP_FMAC2 soap_instantiate__ns1__auction(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__auction(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__saveAuctionResponse
#define SOAP_TYPE__ns1__saveAuctionResponse (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__saveAuctionResponse(struct soap*, const char*, int, const _ns1__saveAuctionResponse *, const char*);
SOAP_FMAC3 _ns1__saveAuctionResponse * SOAP_FMAC4 soap_in__ns1__saveAuctionResponse(struct soap*, const char*, _ns1__saveAuctionResponse *, const char*);

#ifndef soap_write__ns1__saveAuctionResponse
#define soap_write__ns1__saveAuctionResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:saveAuctionResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__saveAuctionResponse
#define soap_read__ns1__saveAuctionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__saveAuctionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__saveAuctionResponse * SOAP_FMAC4 soap_get__ns1__saveAuctionResponse(struct soap*, _ns1__saveAuctionResponse *, const char*, const char*);

#define soap_new__ns1__saveAuctionResponse(soap, n) soap_instantiate__ns1__saveAuctionResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__saveAuctionResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__saveAuctionResponse * SOAP_FMAC2 soap_instantiate__ns1__saveAuctionResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__saveAuctionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__saveAuctionRequest
#define SOAP_TYPE__ns1__saveAuctionRequest (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__saveAuctionRequest(struct soap*, const char*, int, const _ns1__saveAuctionRequest *, const char*);
SOAP_FMAC3 _ns1__saveAuctionRequest * SOAP_FMAC4 soap_in__ns1__saveAuctionRequest(struct soap*, const char*, _ns1__saveAuctionRequest *, const char*);

#ifndef soap_write__ns1__saveAuctionRequest
#define soap_write__ns1__saveAuctionRequest(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:saveAuctionRequest", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__saveAuctionRequest
#define soap_read__ns1__saveAuctionRequest(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__saveAuctionRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__saveAuctionRequest * SOAP_FMAC4 soap_get__ns1__saveAuctionRequest(struct soap*, _ns1__saveAuctionRequest *, const char*, const char*);

#define soap_new__ns1__saveAuctionRequest(soap, n) soap_instantiate__ns1__saveAuctionRequest(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__saveAuctionRequest(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__saveAuctionRequest * SOAP_FMAC2 soap_instantiate__ns1__saveAuctionRequest(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__saveAuctionRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__agent
#define SOAP_TYPE__ns1__agent (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__agent(struct soap*, const char*, int, const _ns1__agent *, const char*);
SOAP_FMAC3 _ns1__agent * SOAP_FMAC4 soap_in__ns1__agent(struct soap*, const char*, _ns1__agent *, const char*);

#ifndef soap_write__ns1__agent
#define soap_write__ns1__agent(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:agent", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__agent
#define soap_read__ns1__agent(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__agent(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__agent * SOAP_FMAC4 soap_get__ns1__agent(struct soap*, _ns1__agent *, const char*, const char*);

#define soap_new__ns1__agent(soap, n) soap_instantiate__ns1__agent(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__agent(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__agent * SOAP_FMAC2 soap_instantiate__ns1__agent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__agent(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__saveAgentResponse
#define SOAP_TYPE__ns1__saveAgentResponse (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__saveAgentResponse(struct soap*, const char*, int, const _ns1__saveAgentResponse *, const char*);
SOAP_FMAC3 _ns1__saveAgentResponse * SOAP_FMAC4 soap_in__ns1__saveAgentResponse(struct soap*, const char*, _ns1__saveAgentResponse *, const char*);

#ifndef soap_write__ns1__saveAgentResponse
#define soap_write__ns1__saveAgentResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:saveAgentResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__saveAgentResponse
#define soap_read__ns1__saveAgentResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__saveAgentResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__saveAgentResponse * SOAP_FMAC4 soap_get__ns1__saveAgentResponse(struct soap*, _ns1__saveAgentResponse *, const char*, const char*);

#define soap_new__ns1__saveAgentResponse(soap, n) soap_instantiate__ns1__saveAgentResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__saveAgentResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__saveAgentResponse * SOAP_FMAC2 soap_instantiate__ns1__saveAgentResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__saveAgentResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__saveAgentRequest
#define SOAP_TYPE__ns1__saveAgentRequest (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__saveAgentRequest(struct soap*, const char*, int, const _ns1__saveAgentRequest *, const char*);
SOAP_FMAC3 _ns1__saveAgentRequest * SOAP_FMAC4 soap_in__ns1__saveAgentRequest(struct soap*, const char*, _ns1__saveAgentRequest *, const char*);

#ifndef soap_write__ns1__saveAgentRequest
#define soap_write__ns1__saveAgentRequest(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:saveAgentRequest", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__saveAgentRequest
#define soap_read__ns1__saveAgentRequest(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__saveAgentRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__saveAgentRequest * SOAP_FMAC4 soap_get__ns1__saveAgentRequest(struct soap*, _ns1__saveAgentRequest *, const char*, const char*);

#define soap_new__ns1__saveAgentRequest(soap, n) soap_instantiate__ns1__saveAgentRequest(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__saveAgentRequest(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__saveAgentRequest * SOAP_FMAC2 soap_instantiate__ns1__saveAgentRequest(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__saveAgentRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__point
#define SOAP_TYPE__ns1__point (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__point(struct soap*, const char*, int, const _ns1__point *, const char*);
SOAP_FMAC3 _ns1__point * SOAP_FMAC4 soap_in__ns1__point(struct soap*, const char*, _ns1__point *, const char*);

#ifndef soap_write__ns1__point
#define soap_write__ns1__point(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:point", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__point
#define soap_read__ns1__point(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__point(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__point * SOAP_FMAC4 soap_get__ns1__point(struct soap*, _ns1__point *, const char*, const char*);

#define soap_new__ns1__point(soap, n) soap_instantiate__ns1__point(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__point(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__point * SOAP_FMAC2 soap_instantiate__ns1__point(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__point(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__func
#define SOAP_TYPE__ns1__func (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__func(struct soap*, const char*, int, const _ns1__func *, const char*);
SOAP_FMAC3 _ns1__func * SOAP_FMAC4 soap_in__ns1__func(struct soap*, const char*, _ns1__func *, const char*);

#ifndef soap_write__ns1__func
#define soap_write__ns1__func(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:func", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__func
#define soap_read__ns1__func(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__func(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__func * SOAP_FMAC4 soap_get__ns1__func(struct soap*, _ns1__func *, const char*, const char*);

#define soap_new__ns1__func(soap, n) soap_instantiate__ns1__func(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__func(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__func * SOAP_FMAC2 soap_instantiate__ns1__func(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__func(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__party
#define SOAP_TYPE__ns1__party (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__party(struct soap*, const char*, int, const _ns1__party *, const char*);
SOAP_FMAC3 _ns1__party * SOAP_FMAC4 soap_in__ns1__party(struct soap*, const char*, _ns1__party *, const char*);

#ifndef soap_write__ns1__party
#define soap_write__ns1__party(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:party", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__party
#define soap_read__ns1__party(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__party(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__party * SOAP_FMAC4 soap_get__ns1__party(struct soap*, _ns1__party *, const char*, const char*);

#define soap_new__ns1__party(soap, n) soap_instantiate__ns1__party(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__party(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__party * SOAP_FMAC2 soap_instantiate__ns1__party(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__party(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__market
#define SOAP_TYPE__ns1__market (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__market(struct soap*, const char*, int, const _ns1__market *, const char*);
SOAP_FMAC3 _ns1__market * SOAP_FMAC4 soap_in__ns1__market(struct soap*, const char*, _ns1__market *, const char*);

#ifndef soap_write__ns1__market
#define soap_write__ns1__market(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:market", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__market
#define soap_read__ns1__market(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__market(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__market * SOAP_FMAC4 soap_get__ns1__market(struct soap*, _ns1__market *, const char*, const char*);

#define soap_new__ns1__market(soap, n) soap_instantiate__ns1__market(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__market(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__market * SOAP_FMAC2 soap_instantiate__ns1__market(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__market(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__marketResponse
#define SOAP_TYPE__ns1__marketResponse (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__marketResponse(struct soap*, const char*, int, const _ns1__marketResponse *, const char*);
SOAP_FMAC3 _ns1__marketResponse * SOAP_FMAC4 soap_in__ns1__marketResponse(struct soap*, const char*, _ns1__marketResponse *, const char*);

#ifndef soap_write__ns1__marketResponse
#define soap_write__ns1__marketResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:marketResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__marketResponse
#define soap_read__ns1__marketResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__marketResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__marketResponse * SOAP_FMAC4 soap_get__ns1__marketResponse(struct soap*, _ns1__marketResponse *, const char*, const char*);

#define soap_new__ns1__marketResponse(soap, n) soap_instantiate__ns1__marketResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__marketResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__marketResponse * SOAP_FMAC2 soap_instantiate__ns1__marketResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__marketResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__marketRequest
#define SOAP_TYPE__ns1__marketRequest (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__marketRequest(struct soap*, const char*, int, const _ns1__marketRequest *, const char*);
SOAP_FMAC3 _ns1__marketRequest * SOAP_FMAC4 soap_in__ns1__marketRequest(struct soap*, const char*, _ns1__marketRequest *, const char*);

#ifndef soap_write__ns1__marketRequest
#define soap_write__ns1__marketRequest(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:marketRequest", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__marketRequest
#define soap_read__ns1__marketRequest(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__marketRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__marketRequest * SOAP_FMAC4 soap_get__ns1__marketRequest(struct soap*, _ns1__marketRequest *, const char*, const char*);

#define soap_new__ns1__marketRequest(soap, n) soap_instantiate__ns1__marketRequest(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__marketRequest(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__marketRequest * SOAP_FMAC2 soap_instantiate__ns1__marketRequest(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__marketRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__date
#define SOAP_TYPE_xsd__date (9)
#endif

#define soap_default_xsd__date(soap, a) soap_default_std__string(soap, a)


#define soap_serialize_xsd__date(soap, a) soap_serialize_std__string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__date(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_xsd__date(struct soap*, const char*, std::string*, const char*);

#ifndef soap_write_xsd__date
#define soap_write_xsd__date(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "xsd:date", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__date(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_read_xsd__date
#define soap_read_xsd__date(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__date(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_xsd__date(struct soap*, std::string *, const char*, const char*);

#define soap_new_xsd__date(soap, n) soap_instantiate_xsd__date(soap, n, NULL, NULL, NULL)


#define soap_delete_xsd__date(soap, p) soap_delete(soap, p)


#define soap_instantiate_xsd__date soap_instantiate_std__string


#define soap_copy_xsd__date soap_copy_std__string

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

#ifndef soap_write_std__string
#define soap_write_std__string(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "string", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_read_std__string
#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#define soap_new_std__string(soap, n) soap_instantiate_std__string(soap, n, NULL, NULL, NULL)


#define soap_delete_std__string(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__market
#define SOAP_TYPE___ns1__market (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__market(struct soap*, struct __ns1__market *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__market(struct soap*, const struct __ns1__market *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__market(struct soap*, const char*, int, const struct __ns1__market *, const char*);
SOAP_FMAC3 struct __ns1__market * SOAP_FMAC4 soap_in___ns1__market(struct soap*, const char*, struct __ns1__market *, const char*);

#ifndef soap_write___ns1__market
#define soap_write___ns1__market(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__market(soap, data), 0) || soap_put___ns1__market(soap, data, "-ns1:market", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__market(struct soap*, const struct __ns1__market *, const char*, const char*);

#ifndef soap_read___ns1__market
#define soap_read___ns1__market(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__market(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__market * SOAP_FMAC4 soap_get___ns1__market(struct soap*, struct __ns1__market *, const char*, const char*);

#define soap_new___ns1__market(soap, n) soap_instantiate___ns1__market(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__market(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__market * SOAP_FMAC2 soap_instantiate___ns1__market(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__market(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__saveSolution
#define SOAP_TYPE___ns1__saveSolution (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__saveSolution(struct soap*, struct __ns1__saveSolution *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__saveSolution(struct soap*, const struct __ns1__saveSolution *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__saveSolution(struct soap*, const char*, int, const struct __ns1__saveSolution *, const char*);
SOAP_FMAC3 struct __ns1__saveSolution * SOAP_FMAC4 soap_in___ns1__saveSolution(struct soap*, const char*, struct __ns1__saveSolution *, const char*);

#ifndef soap_write___ns1__saveSolution
#define soap_write___ns1__saveSolution(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__saveSolution(soap, data), 0) || soap_put___ns1__saveSolution(soap, data, "-ns1:saveSolution", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__saveSolution(struct soap*, const struct __ns1__saveSolution *, const char*, const char*);

#ifndef soap_read___ns1__saveSolution
#define soap_read___ns1__saveSolution(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__saveSolution(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__saveSolution * SOAP_FMAC4 soap_get___ns1__saveSolution(struct soap*, struct __ns1__saveSolution *, const char*, const char*);

#define soap_new___ns1__saveSolution(soap, n) soap_instantiate___ns1__saveSolution(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__saveSolution(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__saveSolution * SOAP_FMAC2 soap_instantiate___ns1__saveSolution(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__saveSolution(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__saveSolutionResponse
#define SOAP_TYPE___ns1__saveSolutionResponse (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__saveSolutionResponse(struct soap*, struct __ns1__saveSolutionResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__saveSolutionResponse(struct soap*, const struct __ns1__saveSolutionResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__saveSolutionResponse(struct soap*, const char*, int, const struct __ns1__saveSolutionResponse *, const char*);
SOAP_FMAC3 struct __ns1__saveSolutionResponse * SOAP_FMAC4 soap_in___ns1__saveSolutionResponse(struct soap*, const char*, struct __ns1__saveSolutionResponse *, const char*);

#ifndef soap_write___ns1__saveSolutionResponse
#define soap_write___ns1__saveSolutionResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__saveSolutionResponse(soap, data), 0) || soap_put___ns1__saveSolutionResponse(soap, data, "-ns1:saveSolutionResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__saveSolutionResponse(struct soap*, const struct __ns1__saveSolutionResponse *, const char*, const char*);

#ifndef soap_read___ns1__saveSolutionResponse
#define soap_read___ns1__saveSolutionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__saveSolutionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__saveSolutionResponse * SOAP_FMAC4 soap_get___ns1__saveSolutionResponse(struct soap*, struct __ns1__saveSolutionResponse *, const char*, const char*);

#define soap_new___ns1__saveSolutionResponse(soap, n) soap_instantiate___ns1__saveSolutionResponse(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__saveSolutionResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__saveSolutionResponse * SOAP_FMAC2 soap_instantiate___ns1__saveSolutionResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__saveSolutionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__saveAgent
#define SOAP_TYPE___ns1__saveAgent (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__saveAgent(struct soap*, struct __ns1__saveAgent *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__saveAgent(struct soap*, const struct __ns1__saveAgent *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__saveAgent(struct soap*, const char*, int, const struct __ns1__saveAgent *, const char*);
SOAP_FMAC3 struct __ns1__saveAgent * SOAP_FMAC4 soap_in___ns1__saveAgent(struct soap*, const char*, struct __ns1__saveAgent *, const char*);

#ifndef soap_write___ns1__saveAgent
#define soap_write___ns1__saveAgent(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__saveAgent(soap, data), 0) || soap_put___ns1__saveAgent(soap, data, "-ns1:saveAgent", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__saveAgent(struct soap*, const struct __ns1__saveAgent *, const char*, const char*);

#ifndef soap_read___ns1__saveAgent
#define soap_read___ns1__saveAgent(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__saveAgent(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__saveAgent * SOAP_FMAC4 soap_get___ns1__saveAgent(struct soap*, struct __ns1__saveAgent *, const char*, const char*);

#define soap_new___ns1__saveAgent(soap, n) soap_instantiate___ns1__saveAgent(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__saveAgent(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__saveAgent * SOAP_FMAC2 soap_instantiate___ns1__saveAgent(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__saveAgent(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__saveBid
#define SOAP_TYPE___ns1__saveBid (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__saveBid(struct soap*, struct __ns1__saveBid *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__saveBid(struct soap*, const struct __ns1__saveBid *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__saveBid(struct soap*, const char*, int, const struct __ns1__saveBid *, const char*);
SOAP_FMAC3 struct __ns1__saveBid * SOAP_FMAC4 soap_in___ns1__saveBid(struct soap*, const char*, struct __ns1__saveBid *, const char*);

#ifndef soap_write___ns1__saveBid
#define soap_write___ns1__saveBid(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__saveBid(soap, data), 0) || soap_put___ns1__saveBid(soap, data, "-ns1:saveBid", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__saveBid(struct soap*, const struct __ns1__saveBid *, const char*, const char*);

#ifndef soap_read___ns1__saveBid
#define soap_read___ns1__saveBid(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__saveBid(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__saveBid * SOAP_FMAC4 soap_get___ns1__saveBid(struct soap*, struct __ns1__saveBid *, const char*, const char*);

#define soap_new___ns1__saveBid(soap, n) soap_instantiate___ns1__saveBid(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__saveBid(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__saveBid * SOAP_FMAC2 soap_instantiate___ns1__saveBid(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__saveBid(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__saveAuction
#define SOAP_TYPE___ns1__saveAuction (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__saveAuction(struct soap*, struct __ns1__saveAuction *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__saveAuction(struct soap*, const struct __ns1__saveAuction *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__saveAuction(struct soap*, const char*, int, const struct __ns1__saveAuction *, const char*);
SOAP_FMAC3 struct __ns1__saveAuction * SOAP_FMAC4 soap_in___ns1__saveAuction(struct soap*, const char*, struct __ns1__saveAuction *, const char*);

#ifndef soap_write___ns1__saveAuction
#define soap_write___ns1__saveAuction(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__saveAuction(soap, data), 0) || soap_put___ns1__saveAuction(soap, data, "-ns1:saveAuction", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__saveAuction(struct soap*, const struct __ns1__saveAuction *, const char*, const char*);

#ifndef soap_read___ns1__saveAuction
#define soap_read___ns1__saveAuction(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__saveAuction(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__saveAuction * SOAP_FMAC4 soap_get___ns1__saveAuction(struct soap*, struct __ns1__saveAuction *, const char*, const char*);

#define soap_new___ns1__saveAuction(soap, n) soap_instantiate___ns1__saveAuction(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__saveAuction(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__saveAuction * SOAP_FMAC2 soap_instantiate___ns1__saveAuction(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__saveAuction(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__marketResponse
#define SOAP_TYPE_PointerTo_ns1__marketResponse (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__marketResponse(struct soap*, _ns1__marketResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__marketResponse(struct soap*, const char *, int, _ns1__marketResponse *const*, const char *);
SOAP_FMAC3 _ns1__marketResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__marketResponse(struct soap*, const char*, _ns1__marketResponse **, const char*);

#ifndef soap_write_PointerTo_ns1__marketResponse
#define soap_write_PointerTo_ns1__marketResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__marketResponse(soap, data), 0) || soap_put_PointerTo_ns1__marketResponse(soap, data, "ns1:marketResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__marketResponse(struct soap*, _ns1__marketResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__marketResponse
#define soap_read_PointerTo_ns1__marketResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__marketResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__marketResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__marketResponse(struct soap*, _ns1__marketResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__marketRequest
#define SOAP_TYPE_PointerTo_ns1__marketRequest (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__marketRequest(struct soap*, _ns1__marketRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__marketRequest(struct soap*, const char *, int, _ns1__marketRequest *const*, const char *);
SOAP_FMAC3 _ns1__marketRequest ** SOAP_FMAC4 soap_in_PointerTo_ns1__marketRequest(struct soap*, const char*, _ns1__marketRequest **, const char*);

#ifndef soap_write_PointerTo_ns1__marketRequest
#define soap_write_PointerTo_ns1__marketRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__marketRequest(soap, data), 0) || soap_put_PointerTo_ns1__marketRequest(soap, data, "ns1:marketRequest", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__marketRequest(struct soap*, _ns1__marketRequest *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__marketRequest
#define soap_read_PointerTo_ns1__marketRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__marketRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__marketRequest ** SOAP_FMAC4 soap_get_PointerTo_ns1__marketRequest(struct soap*, _ns1__marketRequest **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__saveSolutionRequest
#define SOAP_TYPE_PointerTo_ns1__saveSolutionRequest (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__saveSolutionRequest(struct soap*, _ns1__saveSolutionRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__saveSolutionRequest(struct soap*, const char *, int, _ns1__saveSolutionRequest *const*, const char *);
SOAP_FMAC3 _ns1__saveSolutionRequest ** SOAP_FMAC4 soap_in_PointerTo_ns1__saveSolutionRequest(struct soap*, const char*, _ns1__saveSolutionRequest **, const char*);

#ifndef soap_write_PointerTo_ns1__saveSolutionRequest
#define soap_write_PointerTo_ns1__saveSolutionRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__saveSolutionRequest(soap, data), 0) || soap_put_PointerTo_ns1__saveSolutionRequest(soap, data, "ns1:saveSolutionRequest", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__saveSolutionRequest(struct soap*, _ns1__saveSolutionRequest *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__saveSolutionRequest
#define soap_read_PointerTo_ns1__saveSolutionRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__saveSolutionRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__saveSolutionRequest ** SOAP_FMAC4 soap_get_PointerTo_ns1__saveSolutionRequest(struct soap*, _ns1__saveSolutionRequest **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__saveAgentResponse
#define SOAP_TYPE_PointerTo_ns1__saveAgentResponse (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__saveAgentResponse(struct soap*, _ns1__saveAgentResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__saveAgentResponse(struct soap*, const char *, int, _ns1__saveAgentResponse *const*, const char *);
SOAP_FMAC3 _ns1__saveAgentResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__saveAgentResponse(struct soap*, const char*, _ns1__saveAgentResponse **, const char*);

#ifndef soap_write_PointerTo_ns1__saveAgentResponse
#define soap_write_PointerTo_ns1__saveAgentResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__saveAgentResponse(soap, data), 0) || soap_put_PointerTo_ns1__saveAgentResponse(soap, data, "ns1:saveAgentResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__saveAgentResponse(struct soap*, _ns1__saveAgentResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__saveAgentResponse
#define soap_read_PointerTo_ns1__saveAgentResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__saveAgentResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__saveAgentResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__saveAgentResponse(struct soap*, _ns1__saveAgentResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__saveAgentRequest
#define SOAP_TYPE_PointerTo_ns1__saveAgentRequest (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__saveAgentRequest(struct soap*, _ns1__saveAgentRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__saveAgentRequest(struct soap*, const char *, int, _ns1__saveAgentRequest *const*, const char *);
SOAP_FMAC3 _ns1__saveAgentRequest ** SOAP_FMAC4 soap_in_PointerTo_ns1__saveAgentRequest(struct soap*, const char*, _ns1__saveAgentRequest **, const char*);

#ifndef soap_write_PointerTo_ns1__saveAgentRequest
#define soap_write_PointerTo_ns1__saveAgentRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__saveAgentRequest(soap, data), 0) || soap_put_PointerTo_ns1__saveAgentRequest(soap, data, "ns1:saveAgentRequest", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__saveAgentRequest(struct soap*, _ns1__saveAgentRequest *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__saveAgentRequest
#define soap_read_PointerTo_ns1__saveAgentRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__saveAgentRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__saveAgentRequest ** SOAP_FMAC4 soap_get_PointerTo_ns1__saveAgentRequest(struct soap*, _ns1__saveAgentRequest **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__saveBidResponse
#define SOAP_TYPE_PointerTo_ns1__saveBidResponse (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__saveBidResponse(struct soap*, _ns1__saveBidResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__saveBidResponse(struct soap*, const char *, int, _ns1__saveBidResponse *const*, const char *);
SOAP_FMAC3 _ns1__saveBidResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__saveBidResponse(struct soap*, const char*, _ns1__saveBidResponse **, const char*);

#ifndef soap_write_PointerTo_ns1__saveBidResponse
#define soap_write_PointerTo_ns1__saveBidResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__saveBidResponse(soap, data), 0) || soap_put_PointerTo_ns1__saveBidResponse(soap, data, "ns1:saveBidResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__saveBidResponse(struct soap*, _ns1__saveBidResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__saveBidResponse
#define soap_read_PointerTo_ns1__saveBidResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__saveBidResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__saveBidResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__saveBidResponse(struct soap*, _ns1__saveBidResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__saveBidRequest
#define SOAP_TYPE_PointerTo_ns1__saveBidRequest (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__saveBidRequest(struct soap*, _ns1__saveBidRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__saveBidRequest(struct soap*, const char *, int, _ns1__saveBidRequest *const*, const char *);
SOAP_FMAC3 _ns1__saveBidRequest ** SOAP_FMAC4 soap_in_PointerTo_ns1__saveBidRequest(struct soap*, const char*, _ns1__saveBidRequest **, const char*);

#ifndef soap_write_PointerTo_ns1__saveBidRequest
#define soap_write_PointerTo_ns1__saveBidRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__saveBidRequest(soap, data), 0) || soap_put_PointerTo_ns1__saveBidRequest(soap, data, "ns1:saveBidRequest", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__saveBidRequest(struct soap*, _ns1__saveBidRequest *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__saveBidRequest
#define soap_read_PointerTo_ns1__saveBidRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__saveBidRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__saveBidRequest ** SOAP_FMAC4 soap_get_PointerTo_ns1__saveBidRequest(struct soap*, _ns1__saveBidRequest **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__saveAuctionResponse
#define SOAP_TYPE_PointerTo_ns1__saveAuctionResponse (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__saveAuctionResponse(struct soap*, _ns1__saveAuctionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__saveAuctionResponse(struct soap*, const char *, int, _ns1__saveAuctionResponse *const*, const char *);
SOAP_FMAC3 _ns1__saveAuctionResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__saveAuctionResponse(struct soap*, const char*, _ns1__saveAuctionResponse **, const char*);

#ifndef soap_write_PointerTo_ns1__saveAuctionResponse
#define soap_write_PointerTo_ns1__saveAuctionResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__saveAuctionResponse(soap, data), 0) || soap_put_PointerTo_ns1__saveAuctionResponse(soap, data, "ns1:saveAuctionResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__saveAuctionResponse(struct soap*, _ns1__saveAuctionResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__saveAuctionResponse
#define soap_read_PointerTo_ns1__saveAuctionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__saveAuctionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__saveAuctionResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__saveAuctionResponse(struct soap*, _ns1__saveAuctionResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__saveAuctionRequest
#define SOAP_TYPE_PointerTo_ns1__saveAuctionRequest (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__saveAuctionRequest(struct soap*, _ns1__saveAuctionRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__saveAuctionRequest(struct soap*, const char *, int, _ns1__saveAuctionRequest *const*, const char *);
SOAP_FMAC3 _ns1__saveAuctionRequest ** SOAP_FMAC4 soap_in_PointerTo_ns1__saveAuctionRequest(struct soap*, const char*, _ns1__saveAuctionRequest **, const char*);

#ifndef soap_write_PointerTo_ns1__saveAuctionRequest
#define soap_write_PointerTo_ns1__saveAuctionRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__saveAuctionRequest(soap, data), 0) || soap_put_PointerTo_ns1__saveAuctionRequest(soap, data, "ns1:saveAuctionRequest", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__saveAuctionRequest(struct soap*, _ns1__saveAuctionRequest *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__saveAuctionRequest
#define soap_read_PointerTo_ns1__saveAuctionRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__saveAuctionRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__saveAuctionRequest ** SOAP_FMAC4 soap_get_PointerTo_ns1__saveAuctionRequest(struct soap*, _ns1__saveAuctionRequest **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__solution
#define SOAP_TYPE_PointerTo_ns1__solution (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__solution(struct soap*, _ns1__solution *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__solution(struct soap*, const char *, int, _ns1__solution *const*, const char *);
SOAP_FMAC3 _ns1__solution ** SOAP_FMAC4 soap_in_PointerTo_ns1__solution(struct soap*, const char*, _ns1__solution **, const char*);

#ifndef soap_write_PointerTo_ns1__solution
#define soap_write_PointerTo_ns1__solution(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__solution(soap, data), 0) || soap_put_PointerTo_ns1__solution(soap, data, "ns1:solution", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__solution(struct soap*, _ns1__solution *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__solution
#define soap_read_PointerTo_ns1__solution(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__solution(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__solution ** SOAP_FMAC4 soap_get_PointerTo_ns1__solution(struct soap*, _ns1__solution **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__msg
#define SOAP_TYPE_PointerTo_ns1__msg (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__msg(struct soap*, _ns1__msg *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__msg(struct soap*, const char *, int, _ns1__msg *const*, const char *);
SOAP_FMAC3 _ns1__msg ** SOAP_FMAC4 soap_in_PointerTo_ns1__msg(struct soap*, const char*, _ns1__msg **, const char*);

#ifndef soap_write_PointerTo_ns1__msg
#define soap_write_PointerTo_ns1__msg(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__msg(soap, data), 0) || soap_put_PointerTo_ns1__msg(soap, data, "ns1:msg", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__msg(struct soap*, _ns1__msg *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__msg
#define soap_read_PointerTo_ns1__msg(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__msg(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__msg ** SOAP_FMAC4 soap_get_PointerTo_ns1__msg(struct soap*, _ns1__msg **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__partySolution
#define SOAP_TYPE_PointerTo_ns1__partySolution (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__partySolution(struct soap*, _ns1__partySolution *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__partySolution(struct soap*, const char *, int, _ns1__partySolution *const*, const char *);
SOAP_FMAC3 _ns1__partySolution ** SOAP_FMAC4 soap_in_PointerTo_ns1__partySolution(struct soap*, const char*, _ns1__partySolution **, const char*);

#ifndef soap_write_PointerTo_ns1__partySolution
#define soap_write_PointerTo_ns1__partySolution(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__partySolution(soap, data), 0) || soap_put_PointerTo_ns1__partySolution(soap, data, "ns1:partySolution", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__partySolution(struct soap*, _ns1__partySolution *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__partySolution
#define soap_read_PointerTo_ns1__partySolution(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__partySolution(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__partySolution ** SOAP_FMAC4 soap_get_PointerTo_ns1__partySolution(struct soap*, _ns1__partySolution **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__marketSolution
#define SOAP_TYPE_PointerTo_ns1__marketSolution (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__marketSolution(struct soap*, _ns1__marketSolution *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__marketSolution(struct soap*, const char *, int, _ns1__marketSolution *const*, const char *);
SOAP_FMAC3 _ns1__marketSolution ** SOAP_FMAC4 soap_in_PointerTo_ns1__marketSolution(struct soap*, const char*, _ns1__marketSolution **, const char*);

#ifndef soap_write_PointerTo_ns1__marketSolution
#define soap_write_PointerTo_ns1__marketSolution(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__marketSolution(soap, data), 0) || soap_put_PointerTo_ns1__marketSolution(soap, data, "ns1:marketSolution", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__marketSolution(struct soap*, _ns1__marketSolution *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__marketSolution
#define soap_read_PointerTo_ns1__marketSolution(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__marketSolution(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__marketSolution ** SOAP_FMAC4 soap_get_PointerTo_ns1__marketSolution(struct soap*, _ns1__marketSolution **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__bid
#define SOAP_TYPE_PointerTo_ns1__bid (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__bid(struct soap*, _ns1__bid *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__bid(struct soap*, const char *, int, _ns1__bid *const*, const char *);
SOAP_FMAC3 _ns1__bid ** SOAP_FMAC4 soap_in_PointerTo_ns1__bid(struct soap*, const char*, _ns1__bid **, const char*);

#ifndef soap_write_PointerTo_ns1__bid
#define soap_write_PointerTo_ns1__bid(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__bid(soap, data), 0) || soap_put_PointerTo_ns1__bid(soap, data, "ns1:bid", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__bid(struct soap*, _ns1__bid *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__bid
#define soap_read_PointerTo_ns1__bid(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__bid(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__bid ** SOAP_FMAC4 soap_get_PointerTo_ns1__bid(struct soap*, _ns1__bid **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__auction
#define SOAP_TYPE_PointerTo_ns1__auction (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__auction(struct soap*, _ns1__auction *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__auction(struct soap*, const char *, int, _ns1__auction *const*, const char *);
SOAP_FMAC3 _ns1__auction ** SOAP_FMAC4 soap_in_PointerTo_ns1__auction(struct soap*, const char*, _ns1__auction **, const char*);

#ifndef soap_write_PointerTo_ns1__auction
#define soap_write_PointerTo_ns1__auction(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__auction(soap, data), 0) || soap_put_PointerTo_ns1__auction(soap, data, "ns1:auction", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__auction(struct soap*, _ns1__auction *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__auction
#define soap_read_PointerTo_ns1__auction(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__auction(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__auction ** SOAP_FMAC4 soap_get_PointerTo_ns1__auction(struct soap*, _ns1__auction **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__agent
#define SOAP_TYPE_PointerTo_ns1__agent (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__agent(struct soap*, _ns1__agent *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__agent(struct soap*, const char *, int, _ns1__agent *const*, const char *);
SOAP_FMAC3 _ns1__agent ** SOAP_FMAC4 soap_in_PointerTo_ns1__agent(struct soap*, const char*, _ns1__agent **, const char*);

#ifndef soap_write_PointerTo_ns1__agent
#define soap_write_PointerTo_ns1__agent(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__agent(soap, data), 0) || soap_put_PointerTo_ns1__agent(soap, data, "ns1:agent", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__agent(struct soap*, _ns1__agent *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__agent
#define soap_read_PointerTo_ns1__agent(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__agent(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__agent ** SOAP_FMAC4 soap_get_PointerTo_ns1__agent(struct soap*, _ns1__agent **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__point
#define SOAP_TYPE_PointerTo_ns1__point (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__point(struct soap*, _ns1__point *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__point(struct soap*, const char *, int, _ns1__point *const*, const char *);
SOAP_FMAC3 _ns1__point ** SOAP_FMAC4 soap_in_PointerTo_ns1__point(struct soap*, const char*, _ns1__point **, const char*);

#ifndef soap_write_PointerTo_ns1__point
#define soap_write_PointerTo_ns1__point(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__point(soap, data), 0) || soap_put_PointerTo_ns1__point(soap, data, "ns1:point", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__point(struct soap*, _ns1__point *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__point
#define soap_read_PointerTo_ns1__point(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__point(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__point ** SOAP_FMAC4 soap_get_PointerTo_ns1__point(struct soap*, _ns1__point **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__func
#define SOAP_TYPE_PointerTo_ns1__func (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__func(struct soap*, _ns1__func *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__func(struct soap*, const char *, int, _ns1__func *const*, const char *);
SOAP_FMAC3 _ns1__func ** SOAP_FMAC4 soap_in_PointerTo_ns1__func(struct soap*, const char*, _ns1__func **, const char*);

#ifndef soap_write_PointerTo_ns1__func
#define soap_write_PointerTo_ns1__func(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__func(soap, data), 0) || soap_put_PointerTo_ns1__func(soap, data, "ns1:func", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__func(struct soap*, _ns1__func *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__func
#define soap_read_PointerTo_ns1__func(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__func(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__func ** SOAP_FMAC4 soap_get_PointerTo_ns1__func(struct soap*, _ns1__func **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__party
#define SOAP_TYPE_PointerTo_ns1__party (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__party(struct soap*, _ns1__party *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__party(struct soap*, const char *, int, _ns1__party *const*, const char *);
SOAP_FMAC3 _ns1__party ** SOAP_FMAC4 soap_in_PointerTo_ns1__party(struct soap*, const char*, _ns1__party **, const char*);

#ifndef soap_write_PointerTo_ns1__party
#define soap_write_PointerTo_ns1__party(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__party(soap, data), 0) || soap_put_PointerTo_ns1__party(soap, data, "ns1:party", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__party(struct soap*, _ns1__party *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__party
#define soap_read_PointerTo_ns1__party(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__party(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__party ** SOAP_FMAC4 soap_get_PointerTo_ns1__party(struct soap*, _ns1__party **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__market
#define SOAP_TYPE_PointerTo_ns1__market (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__market(struct soap*, _ns1__market *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__market(struct soap*, const char *, int, _ns1__market *const*, const char *);
SOAP_FMAC3 _ns1__market ** SOAP_FMAC4 soap_in_PointerTo_ns1__market(struct soap*, const char*, _ns1__market **, const char*);

#ifndef soap_write_PointerTo_ns1__market
#define soap_write_PointerTo_ns1__market(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__market(soap, data), 0) || soap_put_PointerTo_ns1__market(soap, data, "ns1:market", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__market(struct soap*, _ns1__market *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__market
#define soap_read_PointerTo_ns1__market(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__market(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__market ** SOAP_FMAC4 soap_get_PointerTo_ns1__market(struct soap*, _ns1__market **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTo_ns1__msg
#define SOAP_TYPE_std__vectorTemplateOfPointerTo_ns1__msg (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTo_ns1__msg(struct soap*, std::vector<_ns1__msg * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTo_ns1__msg(struct soap*, const std::vector<_ns1__msg * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTo_ns1__msg(struct soap*, const char*, int, const std::vector<_ns1__msg * >*, const char*);
SOAP_FMAC3 std::vector<_ns1__msg * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTo_ns1__msg(struct soap*, const char*, std::vector<_ns1__msg * >*, const char*);

#define soap_new_std__vectorTemplateOfPointerTo_ns1__msg(soap, n) soap_instantiate_std__vectorTemplateOfPointerTo_ns1__msg(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfPointerTo_ns1__msg(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::vector<_ns1__msg * > * SOAP_FMAC2 soap_instantiate_std__vectorTemplateOfPointerTo_ns1__msg(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTo_ns1__msg(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTo_ns1__partySolution
#define SOAP_TYPE_std__vectorTemplateOfPointerTo_ns1__partySolution (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTo_ns1__partySolution(struct soap*, std::vector<_ns1__partySolution * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTo_ns1__partySolution(struct soap*, const std::vector<_ns1__partySolution * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTo_ns1__partySolution(struct soap*, const char*, int, const std::vector<_ns1__partySolution * >*, const char*);
SOAP_FMAC3 std::vector<_ns1__partySolution * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTo_ns1__partySolution(struct soap*, const char*, std::vector<_ns1__partySolution * >*, const char*);

#define soap_new_std__vectorTemplateOfPointerTo_ns1__partySolution(soap, n) soap_instantiate_std__vectorTemplateOfPointerTo_ns1__partySolution(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfPointerTo_ns1__partySolution(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::vector<_ns1__partySolution * > * SOAP_FMAC2 soap_instantiate_std__vectorTemplateOfPointerTo_ns1__partySolution(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTo_ns1__partySolution(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTo_ns1__point
#define SOAP_TYPE_std__vectorTemplateOfPointerTo_ns1__point (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTo_ns1__point(struct soap*, std::vector<_ns1__point * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTo_ns1__point(struct soap*, const std::vector<_ns1__point * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTo_ns1__point(struct soap*, const char*, int, const std::vector<_ns1__point * >*, const char*);
SOAP_FMAC3 std::vector<_ns1__point * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTo_ns1__point(struct soap*, const char*, std::vector<_ns1__point * >*, const char*);

#define soap_new_std__vectorTemplateOfPointerTo_ns1__point(soap, n) soap_instantiate_std__vectorTemplateOfPointerTo_ns1__point(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfPointerTo_ns1__point(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::vector<_ns1__point * > * SOAP_FMAC2 soap_instantiate_std__vectorTemplateOfPointerTo_ns1__point(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTo_ns1__point(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTo_ns1__party
#define SOAP_TYPE_std__vectorTemplateOfPointerTo_ns1__party (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTo_ns1__party(struct soap*, std::vector<_ns1__party * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTo_ns1__party(struct soap*, const std::vector<_ns1__party * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTo_ns1__party(struct soap*, const char*, int, const std::vector<_ns1__party * >*, const char*);
SOAP_FMAC3 std::vector<_ns1__party * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTo_ns1__party(struct soap*, const char*, std::vector<_ns1__party * >*, const char*);

#define soap_new_std__vectorTemplateOfPointerTo_ns1__party(soap, n) soap_instantiate_std__vectorTemplateOfPointerTo_ns1__party(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfPointerTo_ns1__party(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::vector<_ns1__party * > * SOAP_FMAC2 soap_instantiate_std__vectorTemplateOfPointerTo_ns1__party(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTo_ns1__party(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* End of soapH.h */
